#!/usr/bin/env python3
"""
compile_targets.py - compile rules/clear-100.json into every agent target.

One rule pack in, every file an agent might read out. Nothing here is hand-edited.
Run this after any change to rules/clear-100.json:

    python3 scripts/compile_targets.py
    python3 scripts/compile_targets.py --check    # fail if a target is stale

Targets:
  SKILL.md                       portable Agent Skill (Claude, Codex, Cursor, 40+ agents)
  CLEAR-100.md                   the standard, human readable
  references/rules.md            every rule in full, loaded on demand
  references/lexicons.md         the word lists
  targets/agents-md-snippet.md   paste block for an existing AGENTS.md
  targets/cursor/clearmode.mdc   Cursor project rule, always-apply core
  targets/codex/AGENTS.md        standalone AGENTS.md for Codex CLI
  targets/grok/custom-instructions.txt   fits a custom-instructions box
  targets/system-prompt.txt      paste into any chat or API system prompt
  targets/vale/ClearMode/*.yml   Vale style package
"""

from __future__ import annotations

import argparse
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
PACK = ROOT / "rules" / "clear-100.json"
GEN = "<!-- generated by scripts/compile_targets.py from rules/clear-100.json. do not hand-edit. -->"
GEN_TXT = "# generated by scripts/compile_targets.py from rules/clear-100.json. do not hand-edit."


def load() -> dict:
    return json.loads(PACK.read_text(encoding="utf-8"))


def esc(s: str) -> str:
    return s.replace("|", "\\|").replace("\n", " ")


# --------------------------------------------------------------------------
# shared fragments
# --------------------------------------------------------------------------

def axes_table(p: dict) -> str:
    rows = ["| Axis | What it asks | Weight |", "|---|---|---|"]
    for a in p["axes"].values():
        rows.append(f"| {a['name']} | {esc(a['goal'])} | {a['weight']}% |")
    return "\n".join(rows)


def rule_table(p: dict, axis: str) -> str:
    rows = ["| Rule | Severity | Do this |", "|---|---|---|"]
    for r in p["rules"]:
        if r["axis"] != axis:
            continue
        rows.append(f"| **{r['id']}** {esc(r['title'])} | {r['severity']} | {esc(r['fix'])} |")
    return "\n".join(rows)


def hard_rules(p: dict) -> list[str]:
    """The error-severity rules. These are the ones nothing ships without."""
    return [f"**{r['id']} {r['title']}.** {r['fix']}" for r in p["rules"] if r["severity"] == "error"]


def profile_table(p: dict) -> str:
    keys = ["sentence_words_warn", "paragraph_sentences_warn", "grade_target", "grade_error"]
    labels = {"sentence_words_warn": "Sentence cap", "paragraph_sentences_warn": "Sentences per paragraph",
              "grade_target": "Reading grade target", "grade_error": "Reading grade hard cap"}
    rows = ["| Setting | " + " | ".join(n for n in p["profiles"]) + " |",
            "|---" * (len(p["profiles"]) + 1) + "|"]
    for k in keys:
        rows.append(f"| {labels[k]} | " + " | ".join(str(p["profiles"][n][k]) for n in p["profiles"]) + " |")
    return "\n".join(rows)


def core_loop() -> str:
    return """## The loop

1. Write or read the draft.
2. Run the checker: `python3 scripts/clearcheck.py FILE --profile <general|technical|social|agent>`.
3. Fix every `error`. Fix `warn` unless you can say why the rule is wrong here.
4. Re-run. Stop when the score clears the gate (80 by default) and no errors remain.
5. Never argue with a rule in the draft. Either fix the line or suppress it with `clear: ignore <RULE>` on that line and say why in the commit."""


def three_questions() -> str:
    return """## Before you write a sentence

Ask three things:

1. Would someone outside my field understand this on the first pass?
2. Would a person who did this work say it this way out loud?
3. If I delete this sentence, does the reader lose anything?

A no to any of them means rewrite, not soften."""


# --------------------------------------------------------------------------
# targets
# --------------------------------------------------------------------------

def skill_md(p: dict) -> str:
    hard = "\n".join(f"- {h}" for h in hard_rules(p))
    return f"""---
name: clearmode
description: >
  Write and edit so anyone can read it: plain words, human voice, real structure,
  no filler. Enforces the CLEAR-100 standard on four axes (Plain, Human,
  Structured, Dense) with a zero-dependency checker. Use this skill whenever you
  draft, rewrite, review, or edit any prose a person will read: posts, docs,
  READMEs, emails, newsletters, landing pages, release notes, PR descriptions,
  or instructions for another agent. Also use it when asked to deslop, humanize,
  simplify, or de-jargon existing text.
license: MIT
---

{GEN}

# clearmode

CLEAR-100 v{p['version']}. Four axes, {len(p['rules'])} rules, one checker.

Aerospace built [ASD-STE100](https://www.asd-ste100.org/) so a mechanic on a runway
could not misread a step. It works, and it reads like a machine wrote it, because it
was built for readers who cannot ask a follow-up question. CLEAR-100 keeps that
discipline and adds the two things STE never needed: a human voice, and a page shape
a person will actually scan.

{axes_table(p)}

{three_questions()}

## Hard rules, no exceptions

{hard}

## The rest of the rules

Load `references/rules.md` for all {len(p['rules'])} rules with the reason, the fix, and a
before-and-after for each. Load `references/lexicons.md` for the word lists:
{len(p['slop_words'])} slop words, {len(p['slop_phrases'])} slop phrases,
{len(p['substitutions'])} plain-word swaps, {len(p['jargon'])} jargon glosses.

## Profiles

Pick the profile that matches the reader, then hold its limits.

{profile_table(p)}

{core_loop()}

## What this skill will not do

- It will not make a false claim readable. Wrong and clear is still wrong.
- It will not strip a technical term that is the subject of the sentence. It glosses it once.
- It will not ban contractions. Formal reads synthetic.
- It will not touch code, code blocks, quoted material, or someone else's words.
"""


def clear_100_md(p: dict) -> str:
    preamble = (ROOT / "rules" / "preamble.md").read_text(encoding="utf-8").strip()
    parts = [preamble, "", GEN, ""]
    for key, meta in p["axes"].items():
        parts += [f"## Axis {meta['code']}: {meta['name']} ({meta['weight']}%)", "",
                  meta["goal"], "", rule_table(p, key), ""]
    parts += ["## Profiles", "", profile_table(p), "",
              "## Scoring", "",
              f"Every finding costs its rule weight, multiplied by severity "
              f"(error {p['scoring']['severity_multiplier']['error']}x, "
              f"warn {p['scoring']['severity_multiplier']['warn']}x, "
              f"review {p['scoring']['severity_multiplier']['review']}x), "
              f"normalized per 250 words. Each axis starts at 100. The document score is the "
              f"weighted mean of the four axes. Default gate is {p['scoring']['gate_default']}.", ""]
    rows = ["| Score | Band | Verdict |", "|---|---|---|"]
    for b in p["scoring"]["grade_bands"]:
        rows.append(f"| {b['min']}+ | {b['label']} | {b['verdict']} |")
    parts += ["\n".join(rows), ""]
    return "\n".join(parts)


def references_rules_md(p: dict) -> str:
    out = [GEN, "", f"# CLEAR-100 rules in full", "",
           f"{len(p['rules'])} rules. Severity `error` blocks a ship. `warn` needs a reason to keep. "
           f"`review` is a prompt to look, not a verdict.", ""]
    for key, meta in p["axes"].items():
        out += [f"## {meta['name']}", ""]
        for r in p["rules"]:
            if r["axis"] != key:
                continue
            out += [f"### {r['id']} {r['title']}", "",
                    f"`{r['severity']}`, weight {r['weight']}, detector `{r['detector']}`", "",
                    f"**Why.** {r['why']}", "",
                    f"**Fix.** {r['fix']}", ""]
            if r.get("bad"):
                out += ["```text", f"BAD:  {r['bad']}", f"GOOD: {r.get('good','')}", "```", ""]
    return "\n".join(out)


def references_lexicons_md(p: dict) -> str:
    def block(title: str, items, note: str = "") -> list[str]:
        return [f"## {title} ({len(items)})", "", note, "", "```text",
                "\n".join(sorted(items)), "```", ""]

    out = [GEN, "", "# CLEAR-100 lexicons", "",
           "The checker reads these from `rules/clear-100.json`. This file is for you to read.", ""]
    out += block("Slop words", p["slop_words"],
                 "Frequency of these spiked after 2022. Readers who use models daily register them as a signature.")
    out += block("Slop phrases", p["slop_phrases"], "Whole clauses that carry no information.")
    out += block("Banned sentence openers", p["banned_openers"], "Transition words reached for when there is nothing to add.")
    out += block("Assistant voice", p["assistant_voice"], "Chat-window residue. Never appears in published text.")
    out += block("Promotional adjectives", p["promo_words"], "Travel-brochure vocabulary applied to software.")
    out += block("Filler words", p["filler_words"], "Each one weakens the word it is trying to strengthen.")
    out += ["## Slop replacements ({})".format(len(p["slop_replacements"])), "",
            "What to say instead of a banned word, when the specific thing is not available.", "",
            "| Instead of | Write |", "|---|---|"]
    for k, v in sorted(p["slop_replacements"].items()):
        out.append(f"| {k} | {v} |")
    out += ["", "## Plain-word swaps ({})".format(len(p["substitutions"])), "",
            "| Instead of | Write |", "|---|---|"]
    for k, v in sorted(p["substitutions"].items()):
        out.append(f"| {k} | {v} |")
    out += ["", "## Jargon glosses ({})".format(len(p["jargon"])), "",
            "Use the gloss once, on first use, then use the term freely.", "",
            "| Term | Gloss |", "|---|---|"]
    for k, v in sorted(p["jargon"].items()):
        out.append(f"| {k} | {v} |")
    return "\n".join(out) + "\n"


def core_block(p: dict) -> str:
    """The shared always-on block. Same text in AGENTS.md, Codex, and elsewhere."""
    g = p["profiles"]["general"]
    hard = "\n".join(f"- {h}" for h in hard_rules(p))
    return f"""Every word a person reads passes four axes: Plain, Human, Structured, Dense.

{hard}

Sentence cap {g['sentence_words_warn']} words. Paragraph cap {g['paragraph_sentences_warn']} sentences. Reading grade target {g['grade_target']}.
Three or more parallel items become a list. Sequences become numbered steps.
Gloss a term of art once, in plain words, on first use. Keep contractions.
Vary sentence length. Delete any sentence a reader could have guessed.

Check prose before you commit it:

```bash
python3 scripts/clearcheck.py <file> --profile general
```

Full rules in `references/rules.md`. Word lists in `references/lexicons.md`."""


def agents_snippet(p: dict) -> str:
    return f"""{GEN}

<!-- CLEAR-100 begin. Paste this block into your AGENTS.md. -->
## Writing rules (CLEAR-100 v{p['version']})

{core_block(p)}
<!-- CLEAR-100 end -->
"""


def codex_agents(p: dict) -> str:
    return f"""{GEN}

# AGENTS.md

## Writing rules (CLEAR-100 v{p['version']})

{core_block(p)}

## Notes for Codex CLI

This file is the whole contract for prose in this repo. Codex reads the nearest
AGENTS.md, so drop a copy in any package that ships user-facing text.
"""


def cursor_mdc(p: dict) -> str:
    """Always-apply Cursor rule. Kept deliberately short: it loads on every request."""
    body = f"""Write so anyone can read it. CLEAR-100 v{p['version']}, four axes: Plain, Human, Structured, Dense.

Never ship: em-dashes, slop words (delve, robust, seamless, leverage, unlock, game-changer),
slop phrases (in today's fast-paced, it's worth noting), negative parallelism (not just X but Y),
assistant voice (hope this helps, great question), model self-reference, or a first sentence
with no number, name, or claim in it.

Always: active voice, one instruction per sentence, sentences under {p['profiles']['general']['sentence_words_warn']} words,
paragraphs under {p['profiles']['general']['paragraph_sentences_warn']} sentences, reading grade at or under {p['profiles']['general']['grade_target']}.
Gloss any term of art once in plain words. Keep contractions. Three parallel items become a list.
Sequences become numbered steps. Delete any sentence a reader could have guessed.

Check with: python3 scripts/clearcheck.py FILE --profile general
Full rules: references/rules.md"""
    wc = len(body.split())
    assert wc < 220, f"cursor always-apply rule too long: {wc} words"
    return f"""---
description: CLEAR-100 writing standard. Plain, human, structured, dense.
globs: ["**/*.md", "**/*.mdx", "**/*.txt", "**/*.html"]
alwaysApply: true
---

{body}
"""




def compact(p: dict, budget: int) -> str:
    """One paste-anywhere block that fits a character budget."""
    head = f"""Write so anyone can read it. Standard: CLEAR-100 v{p['version']}. Four axes.

PLAIN. Active voice. One instruction per sentence. Under {p['profiles']['general']['sentence_words_warn']} words a sentence.
Reading grade {p['profiles']['general']['grade_target']} or lower. Use the short word (use, not utilize). Gloss any term of art
once in plain words on first use. Expand an acronym once. Keep contractions.

HUMAN. No em-dashes. No curly quotes. No "not just X but Y". No "serves as" for "is".
No "Furthermore/Moreover/Additionally" openers. No "hope this helps" or "great question".
No "in conclusion". No vague sources ("experts say"). Vary sentence length: put a four-word
sentence next to a long one. Never reference yourself as an AI.

STRUCTURED. Three or more parallel items become a bulleted list. Sequences become numbered
steps. Comparisons become a table. Paragraphs stay under {p['profiles']['general']['paragraph_sentences_warn']} sentences.
Sentence-case headings, no Title Case. No emoji as bullets or headings. Bold at most one thing
per section. Long pieces open with the answer in one to three lines.

DENSE. Every sentence needs a number, a name, a mechanism, or a consequence. If deleting a
sentence loses nothing, delete it. The first sentence is the only one everyone reads: spend it
on the claim, never on setup. Cut very, really, basically, simply, actually.

BANNED WORDS: """
    words = []
    for w in p["slop_words"]:
        candidate = ", ".join(words + [w])
        if len(head) + len(candidate) + 2 > budget:
            break
        words.append(w)
    return head + ", ".join(words) + "."


def vale_files(p: dict) -> dict[str, str]:
    def existence(name: str, msg: str, level: str, items, ignorecase=True) -> str:
        lines = [GEN_TXT, f"extends: existence", f"message: \"{msg}\"", f"level: {level}",
                 f"ignorecase: {str(ignorecase).lower()}", "tokens:"]
        lines += [f"  - {t}" for t in sorted(items)]
        return "\n".join(lines) + "\n"

    def substitution() -> str:
        lines = [GEN_TXT, "extends: substitution", "message: \"Use '%s' instead of '%s'.\"",
                 "level: warning", "ignorecase: true", "swap:"]
        for k, v in sorted(p["substitutions"].items()):
            lines.append(f"  {k}: {v}")
        return "\n".join(lines) + "\n"

    return {
        "SlopWords.yml": existence("SlopWords", "CLEAR-100 H1: '%s' is slop vocabulary. Say the specific thing.", "error", p["slop_words"]),
        "SlopPhrases.yml": existence("SlopPhrases", "CLEAR-100 H2: '%s' carries no information. Delete it.", "error", p["slop_phrases"]),
        "Openers.yml": existence("Openers", "CLEAR-100 H3: '%s' is a canned opener.", "warning", p["banned_openers"]),
        "AssistantVoice.yml": existence("AssistantVoice", "CLEAR-100 H12: '%s' is chat residue, not published text.", "error", p["assistant_voice"]),
        "PromoWords.yml": existence("PromoWords", "CLEAR-100 H9: '%s' is brochure language. Give the measurement.", "warning", p["promo_words"]),
        "Filler.yml": existence("Filler", "CLEAR-100 D5: '%s' weakens the word it modifies.", "suggestion", p["filler_words"]),
        "PlainWords.yml": substitution(),
    }


# --------------------------------------------------------------------------
# driver
# --------------------------------------------------------------------------

def build(p: dict) -> dict[str, str]:
    out = {
        "SKILL.md": skill_md(p),
        "CLEAR-100.md": clear_100_md(p),
        "references/rules.md": references_rules_md(p),
        "references/lexicons.md": references_lexicons_md(p),
        "targets/agents-md-snippet.md": agents_snippet(p),
        "targets/cursor/clearmode.mdc": cursor_mdc(p),
        "targets/codex/AGENTS.md": codex_agents(p),
        "targets/grok/custom-instructions.txt": compact(p, 3000) + "\n",
        "targets/system-prompt.txt": compact(p, 6000) + "\n",
    }
    for name, body in vale_files(p).items():
        out[f"targets/vale/ClearMode/{name}"] = body
    out["targets/vale/.vale.ini"] = (
        GEN_TXT + "\nStylesPath = .\nMinAlertLevel = suggestion\n\n"
        "[*.{md,mdx,txt,html}]\nBasedOnStyles = ClearMode\n"
    )
    out["targets/claude/SKILL.md"] = out["SKILL.md"]
    return out


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(prog="compile_targets")
    ap.add_argument("--check", action="store_true", help="exit 1 if any target is stale")
    a = ap.parse_args(argv)

    p = load()
    files = build(p)
    stale = []
    for rel, body in files.items():
        path = ROOT / rel
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == body:
            continue
        stale.append(rel)
        if not a.check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(body, encoding="utf-8")

    if a.check:
        if stale:
            print("stale targets, run scripts/compile_targets.py:")
            for s in stale:
                print(f"  {s}")
            return 1
        print(f"all {len(files)} targets current")
        return 0

    for rel in sorted(files):
        mark = "updated" if rel in stale else "same"
        print(f"  {mark:<8} {rel}")
    print(f"\n{len(stale)} of {len(files)} targets written from rules/clear-100.json")
    return 0


if __name__ == "__main__":
    sys.exit(main())
